#!/bin/bash
#Extract propositional variables from EFSM

events=$(cat $1 | grep "^    " | grep "\\-> .* \\[label" | sed 's/.*= "//g; s/"];//g' | sort | uniq)
actions=$(cat plants/plant-5-0.dot | grep "^    " | grep -v "\\->" | grep -v "    init" | grep -v "    node" | sed 's/^.* : //g; s/".*$//g; s/, /\n/g' | sort | uniq)

PROP=

for e in $events ; do
   PROP="$PROP event($e)"
done

for a in $actions ; do
   PROP="$PROP action($a)"
done

echo $PROP
